name: financial_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  
  - pandas>=1.4.0
  - pdfplumber>=0.10.0
  - pytorch>=2.0.0
  - tqdm>=4.65.0
  - python-dotenv>=1.0.0
  - pip>=23.1.2
  - pip:
    - langchain-core>=0.1.0
    - langchain-community>=0.0.11
    - langchain-chroma>=0.0.5
    - sentence-transformers>=2.2.2
    - chromadb>=0.4.15
    - pypdf2>=3.0.0  # or pdfplumber